# This file was generated by GoReleaser. DO NOT EDIT.
cask "shpyrd" do
  version "0.9.55"

  on_macos do
    on_arm do
      sha256 "401ff42aadf23e58d08d2aaf23850fd2e15fadef2151c76aab501093121b1333"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "927a117ccda59a46488cbd124c7208f899bf59d7ee54aa5b204eee31e5bb4133"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ef2bb00cb741f22c4d41cd9accea23559352fcc9adcda11b93e65513b1c2c5ff"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef2f6660f0215091b09bd6e050666b215b7e2a7b9420827ca842b3c7e202fbd4"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "shpyrd"
  desc "Open-source Cloud PaaS on Kubernetes: deploy, run and observe applications and agents from one place. Includes shpyrd (developer CLI) and shpyrd-ctl (operator CLI)."
  homepage "https://shpyrd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shpyrd"
  binary "shpyrd-ctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd-ctl"]
    end
  end

  # No zap stanza required
end
