# This file was generated by GoReleaser. DO NOT EDIT.
cask "shpyrd" do
  version "0.9.22"

  on_macos do
    on_arm do
      sha256 "b097b79b9147b0c430f0af257f40b19e3f34e5d1cbb1f382caa675e70fdbf2c3"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ea3c8484496a167a9c385a0d8fbd52e60f9d1ecd84a9a1011850187980789b5"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5ae4ac1baf417b8f544cc0fd15eeb32bc95e8b50f55aedd2766b2d69a28a75ce"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "59bb0c636597cc9e84bbf55724af9ad4ca797bfbe88e389fffd820367e327be7"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "shpyrd"
  desc "Open-source Cloud PaaS on Kubernetes: deploy, run and observe applications and agents from one place. Includes shpyrd (developer CLI) and shpyrd-ctl (operator CLI)."
  homepage "https://shpyrd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shpyrd"
  binary "shpyrd-ctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd-ctl"]
    end
  end

  # No zap stanza required
end
