# This file was generated by GoReleaser. DO NOT EDIT.
cask "shpyrd" do
  version "0.9.76"

  on_macos do
    on_arm do
      sha256 "6615a7ca5731da8e5f650c1a316f02bacb83d2193b13f65d392e9f435e93ca3a"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6485fb06e197ece16f5ffd96ff43fc1c757d1a9d50b530f35f2500d8443a8be"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bec05db9b762b0959fc0363a890b66fafd048511bc0186d2d68710ed75b2b474"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a3f6c45fea8c8e81ae4cac38bcaacdee16abe32908c4dd5a5cbc4a7428e4f470"
      url "https://github.com/shpyrd-io/shpyrd/releases/download/v#{version}/shpyrd_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "shpyrd"
  desc "Open-source Cloud PaaS on Kubernetes: deploy, run and observe applications and agents from one place. Includes shpyrd (developer CLI) and shpyrd-ctl (operator CLI)."
  homepage "https://shpyrd.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shpyrd"
  binary "shpyrd-ctl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shpyrd-ctl"]
    end
  end

  # No zap stanza required
end
